pipeline {
    agent none
    stages {
        stage('Build') {
            agent {
                docker {
                    image 'python:2.7'
                }
            }
            steps {
                sh 'pip install -r requirements.txt'
                sh 'pip install -e .'
            }
        }
        stage('Test') {
            agent {
                docker {
                    image 'qnib/pytest'
                }
            }
            steps {
                sh 'py.test --verbose --junit-xml test-reports/results.xml tests/*.py'
            }
            post {
                always {
                    junit 'test-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            agent {
                docker {
                    image 'python:2.7'
                }
            }
            steps {
                sh 'python setup.py sdist'
            }
            post {
                success {
                    archiveArtifacts 'dist/*.tar.gz' 
                }
            }
        }
    }
}
